### ISSUE TITLE
Problem trying to run demo with Java 8

### ISSUE THREAD

**Issue by csantosbh** [FedUni/caliko#21]
I'm not sure I'm following the right steps to run the jar files provided with the releases (I don't have a proper environment for building java solutions in my machine, so I just wanted to test the built solutions), but this is the output of my attempts on Windows 10:

```
java -jar caliko-demo-1.3.6-jar-with-dependencies.jar
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: au/edu/federation/caliko/demo/Application has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
```

This is my version of java:
```
java -version
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)
```

**Comment by alansley** [comment]
From your error message: "Application has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0"

Looks like you need to update your JRE (Java Runtime Environment) - try:
https://www.oracle.com/java/technologies/javase-jre8-downloads.html

Let me know how you get on!
